# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

jdk:
  - openjdk12

services:
#  - postgresql

before_install:
 # - psql -c 'create database tracker;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -admin@it-kras.ru
    on_success: never # default: change
    on_failure: always # default: always
   
env:
  global:
    - CODECOV_TOKEN="ec5593e7-3597-4de6-b3d8-675390f7a655"