# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

jdk:
  - openjdk13

services:
#  - postgresql

before_install:
 # - psql -c 'create database users;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -admin@it-kras.ru
    on_success: never # default: change
    on_failure: always # default: always
   
env:
  global:
    - CODECOV_TOKEN="773ef534-433a-4c5f-a075-4f61c7bab9ba"